module.exports = {
  future: {
    purgeLayersByDefault: true,
    removeDeprecatedGapUtilities: true,
  },
  purge: [],
  theme: {
    extend: {},
  },
  variants: {
    accessibility: ["focus"],
    alignContent: [],
    alignItems: [],
    alignSelf: [],
    appearance: [],
    backgroundAttachment: [],
    backgroundClip: [],
    backgroundColor: ["hover", "focus"],
    backgroundImage: [],
    gradientColorStops: ["hover", "focus"],
    backgroundOpacity: ["hover", "focus"],
    backgroundPosition: [],
    backgroundRepeat: [],
    backgroundSize: [],
    borderCollapse: [],
    borderColor: ["hover", "focus"],
    borderOpacity: ["hover", "focus"],
    borderRadius: [],
    borderStyle: [],
    borderWidth: [],
    boxShadow: ["hover", "focus"],
    boxSizing: [],
    container: [],
    cursor: [],
    display: [],
    divideColor: [],
    divideOpacity: [],
    divideStyle: [],
    divideWidth: [],
    fill: [],
    flex: [],
    flexDirection: [],
    flexGrow: [],
    flexShrink: [],
    flexWrap: [],
    float: [],
    clear: [],
    fontFamily: [],
    fontSize: [],
    fontSmoothing: [],
    fontVariantNumeric: [],
    fontStyle: [],
    fontWeight: ["hover", "focus"],
    height: [],
    inset: [],
    justifyContent: [],
    justifyItems: [],
    justifySelf: [],
    letterSpacing: [],
    lineHeight: [],
    listStylePosition: [],
    listStyleType: [],
    margin: [],
    maxHeight: [],
    maxWidth: [],
    minHeight: [],
    minWidth: [],
    objectFit: [],
    objectPosition: [],
    opacity: ["hover", "focus"],
    order: [],
    outline: ["focus"],
    overflow: [],
    overscrollBehavior: [],
    padding: [],
    placeContent: [],
    placeItems: [],
    placeSelf: [],
    placeholderColor: ["focus"],
    placeholderOpacity: ["focus"],
    pointerEvents: [],
    position: [],
    resize: [],
    space: [],
    stroke: [],
    strokeWidth: [],
    tableLayout: [],
    textAlign: [],
    textColor: ["hover", "focus"],
    textOpacity: ["hover", "focus"],
    textDecoration: ["hover", "focus"],
    textTransform: [],
    userSelect: [],
    verticalAlign: [],
    visibility: [],
    whitespace: [],
    width: [],
    wordBreak: [],
    zIndex: [],
    gap: [],
    gridAutoFlow: [],
    gridTemplateColumns: [],
    gridColumn: [],
    gridColumnStart: [],
    gridColumnEnd: [],
    gridTemplateRows: [],
    gridRow: [],
    gridRowStart: [],
    gridRowEnd: [],
    transform: [],
    transformOrigin: [],
    scale: ["hover", "focus"],
    rotate: ["hover", "focus"],
    translate: ["hover", "focus"],
    skew: ["hover", "focus"],
    transitionProperty: [],
    transitionTimingFunction: [],
    transitionDuration: [],
    transitionDelay: [],
    animation: [],
  },
  plugins: [],
};
